package tasks_formal;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.util.ArrayList;
import java.util.List;
import java.lang.String;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gamal
 */
public class GuiTask extends javax.swing.JFrame {

    /**
     * Creates new form GuiTask
     */
        static Scanner myObj = new Scanner(System.in);
        
    public GuiTask() {
        initComponents();
//        jButton3.disable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inputFiled = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        text_code = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        full_table = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(20, 30, 39));

        inputFiled.setBackground(new java.awt.Color(238, 237, 222));
        inputFiled.setForeground(new java.awt.Color(20, 30, 39));
        inputFiled.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputFiled.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        inputFiled.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputFiledFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputFiledFocusLost(evt);
            }
        });
        inputFiled.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inputFiledMouseExited(evt);
            }
        });
        inputFiled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFiledActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(5, 89, 91));
        jButton1.setForeground(new java.awt.Color(238, 237, 222));
        jButton1.setText("Generate Code");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        table.setBackground(new java.awt.Color(32, 50, 57));
        table.setForeground(new java.awt.Color(238, 237, 222));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table.setGridColor(new java.awt.Color(238, 237, 222));
        table.setSelectionForeground(new java.awt.Color(255, 51, 0));
        jScrollPane1.setViewportView(table);

        text_code.setBackground(new java.awt.Color(32, 50, 57));
        text_code.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        text_code.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(text_code);

        jButton2.setBackground(new java.awt.Color(6, 44, 48));
        jButton2.setForeground(new java.awt.Color(238, 237, 222));
        jButton2.setText("Copy Code");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(32, 50, 57));
        jButton3.setForeground(new java.awt.Color(238, 237, 222));
        jButton3.setText("Add To Table");
        jButton3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(20, 30, 39))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        full_table.setBackground(new java.awt.Color(238, 237, 222));
        full_table.setForeground(new java.awt.Color(20, 30, 39));
        full_table.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        full_table.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setBackground(new java.awt.Color(238, 237, 222));
        jLabel1.setForeground(new java.awt.Color(238, 237, 222));
        jLabel1.setText("Enter State ");

        jLabel2.setBackground(new java.awt.Color(238, 237, 222));
        jLabel2.setForeground(new java.awt.Color(238, 237, 222));
        jLabel2.setText("Enter Token");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(full_table, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputFiled))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(full_table, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        //get mode tanble
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        
        if(full_table.getText().length()!=inputFiled.getText().length()){
        JOptionPane.showMessageDialog(null,"Please Enter Size Of Token is equal to States");  
        }
        try{
        Integer.valueOf(full_table.getText());
        String []fulltable = full_table.getText().trim().split("");
        //add row
        model.addRow(fulltable);
        } catch (NumberFormatException e) {
        //not an integer
        JOptionPane.showMessageDialog(null,"Please Enter Size States Number Only");  
    }
       

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //copy to clipboard
      
        
        String myString = text_code.getText();
        //copy code
        StringSelection stringSelection = new StringSelection(myString);
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(stringSelection, null);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // get object frm class GetData
          if(full_table.getText().length()!=inputFiled.getText().length()){
            JOptionPane.showMessageDialog(null,"Please Enter Size Of Token is equal to States");  
            }
        try{
            Integer.valueOf(full_table.getText());
        } catch (NumberFormatException e) {
        //not an integer
            JOptionPane.showMessageDialog(null,"Please Enter Size States Number Only");  
        }
        GetData getData=new GetData();
        //get Data Text Filed And Transform into Array
        String[] token=inputFiled.getText().trim().split("");
        //set header of array
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int getRowCount=model.getRowCount();
        int getColumnCount=model.getColumnCount();
        //init array row =state and col=token
        int[][] arr = new int[getRowCount][getColumnCount];
        for (int row = 0; row <getRowCount; row++) {
            for (int col = 0; col < getColumnCount; col++) {
                arr[row][col]=Integer.parseInt((String) model.getValueAt(row, col));
            }
        }
        //call function DVA and send data there
        String code= getData.DVA(getRowCount,arr,token);
        text_code.setText(code);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void inputFiledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFiledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFiledActionPerformed

    private void inputFiledMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputFiledMouseExited
        // TODO add your handling code here:
        //         String[] token=inputFiled.getText().trim().split("");
        //        //set header of array
        //        DefaultTableModel model = (DefaultTableModel) table.getModel();
        //        for (int i = 0; i < token.length; i++) {
            //            model.addColumn(token[i]);
            //                System.out.println(token[i]+" ");
            //        }

    }//GEN-LAST:event_inputFiledMouseExited

    private void inputFiledFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputFiledFocusLost
        // TODO add your handling code here:

        String[] token=inputFiled.getText().trim().split("");
        //set header of array
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        for (int i = 0; i < token.length; i++) {
            model.addColumn(token[i]);
//            System.out.println(token[i]+" ");
        }
        
    }//GEN-LAST:event_inputFiledFocusLost

    private void inputFiledFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputFiledFocusGained
        // TODO add your handling code here:
        //         String[] token=inputFiled.getText().trim().split("");
        //        //set header of array
        //        DefaultTableModel model = (DefaultTableModel) table.getModel();
        //        for (int i = 0; i < token.length; i++) {
            //            model.addColumn(token[i]);
            //        }
    }//GEN-LAST:event_inputFiledFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new GuiTask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField full_table;
    private javax.swing.JTextField inputFiled;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    private javax.swing.JTextPane text_code;
    // End of variables declaration//GEN-END:variables
}
